[package]
name = "yapyrg"
version = "0.1.0"
edition = "2024"

[lib]
name = "yapyrg"
crate-type = ["cdylib"]

[dependencies]
grep-regex = "0.1.14"
grep-searcher = "0.1.16"
ignore = "0.4.25"
pyo3 = { version = "0.27.0", features = ["extension-module"] }
